#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : testpath
Version  : 0.3.1
Release  : 3
URL      : http://pypi.debian.net/testpath/testpath-0.3.1.tar.gz
Source0  : http://pypi.debian.net/testpath/testpath-0.3.1.tar.gz
Summary  : Test utilities for code working with files and commands
Group    : Development/Tools
License  : MIT
Requires: testpath-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Testpath is a collection of utilities for Python code working with files and commands.

%package python
Summary: python components for the testpath package.
Group: Default

%description python
python components for the testpath package.


%prep
%setup -q -n testpath-0.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505684850
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
